/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Monster;

/**
 *
 * @author fran
 */
public class MonsterView extends javax.swing.JPanel {
    
    // Variables
    private Monster monsterModel;

    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
                
        initComponents();
        
        // El diseño tiene los labels para poner el texto.
        // Al usar las imágenes, se dejan sin texto en lugar de eliminarlos,
        // para usarlo en caso que sea necesario
        jLabelMonsterCombatLevel.setText("");
        jLabelMonsterLevelCultist.setText("");
        jLabelMonsterName.setText("");
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMonsterName = new javax.swing.JLabel();
        jLabelMonsterCombatLevel = new javax.swing.JLabel();
        jLabelMonsterLevelCultist = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        prizeViewMonster = new GUI.PrizeView();
        badConsequenceViewMonster = new GUI.BadConsequenceView();
        jPanel3 = new javax.swing.JPanel();
        jLabelIcon = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);

        jLabelMonsterName.setText("Name");
        jPanel1.add(jLabelMonsterName);

        jLabelMonsterCombatLevel.setText("Combat Level");
        jPanel1.add(jLabelMonsterCombatLevel);

        jLabelMonsterLevelCultist.setText("Level Cultist");
        jPanel1.add(jLabelMonsterLevelCultist);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(prizeViewMonster);

        badConsequenceViewMonster.setOpaque(false);
        jPanel2.add(badConsequenceViewMonster);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabelIcon, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Setters
    public void setMonster(Monster m){
        
        monsterModel = m;
        
        // No se pone el texto porque se muestra la imagen
        //jLabelMonsterName.setText(m.getName());
        //jLabelMonsterCombatLevel.setText(m.getCombatLevel()+"");
        //jLabelMonsterLevelCultist.setText(m.getCombatLevelAgainstCultistPlayer()+"");
        
        prizeViewMonster.setPrize(m.getPrize());
        badConsequenceViewMonster.setBadConsequence(m.getBadConsequence());
     
        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monsters/"+m.getName()+".jpg")));
        
        repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceViewMonster;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelMonsterCombatLevel;
    private javax.swing.JLabel jLabelMonsterLevelCultist;
    private javax.swing.JLabel jLabelMonsterName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private GUI.PrizeView prizeViewMonster;
    // End of variables declaration//GEN-END:variables
}
