/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Prize;

/**
 *
 * @author fran
 */
public class PrizeView extends javax.swing.JPanel {
   
    // Variables
    private Prize prizeModel;

    
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        
        initComponents();
        
        // El diseño tiene los labels para poner el texto.
        // Al usar las imágenes, se dejan sin texto en lugar de eliminarlos,
        // para usarlo en caso que sea necesario
        jLabelPrizeLevel.setText("");
        jLabelPrizeTreasures.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPrizeTreasures = new javax.swing.JLabel();
        jLabelPrizeLevel = new javax.swing.JLabel();

        setOpaque(false);

        jLabelPrizeTreasures.setText("Treasures");
        add(jLabelPrizeTreasures);

        jLabelPrizeLevel.setText("Level");
        add(jLabelPrizeLevel);
    }// </editor-fold>//GEN-END:initComponents

    // Setters
    public void setPrize(Prize p){
        
        prizeModel = p;
        
        // No se pone el texto porque se muestra la imagen
        //jLabelPrizeTreasures.setText(p.getTreasures() + "");
        //jLabelPrizeLevel.setText(p.getLevel() + "");
        
        repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPrizeLevel;
    private javax.swing.JLabel jLabelPrizeTreasures;
    // End of variables declaration//GEN-END:variables
}
